pipeline:
  stages:
    - build
      test
      deploy
  jobs:
    build:
      runsOn: ubuntu-latest
      steps:
        - npm install
          npm run build

    deploy:
      runsOn: ubuntu-latest
