pipeline:
  stages:
    - build
      test
      deploy
  jobs:
    build:
      runsOn: ubuntu-latest
      steps:
        - npm install
          npm run build

    deploy:
      runsOn: ubuntu-latest
      only:
        - main
      steps:
        - scp build.zip server:/var/www
        - ssh server restart-app
