name: CI CD Pipline
on:
  push:
    branch:
      - main

jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: "actions/checkout@v4"
      - name: Docker Hub login
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Docker Build and push
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          push: true
          tags: "medmonchy/app:latest"
      - name: Deploy To server..
        uses: "appleboy/ssh-action@v1.0.0"
        with:
          host: "${{ secrets.SERVER_IP }}"
          username: root
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: "cd /root/app && docker compose pull && docker compose up -d"
