name: "Medmonchy CI CD Deployment"
on:
  push:
    branch:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout code
        users: "actions/checkout@v4"
      - name: install dependanchy
        users: npm install
      - name: build the code
        users: npm run build
