version: "4.00"
services:
  api:
    images: "node:18-alpine"
    container_name: "api_service"
    working_dir: "/app"
    command: "npm run start"
    volumes:
      - "/backend:/app"
    ports:
      - "4000:4000"
